--CREATE A Table for Employees and for Reimbursements. 
CREATE TABLE EMPLOYEE_D (
    E_ID INTEGER PRIMARY KEY,
    E_USERNAME VARCHAR(20),
    E_PASSWORD VARCHAR(20), 
    E_EMAIL VARCHAR2(50),
    MANAGER_ID INTEGER 
);
/

CREATE TABLE REIMBURSEMENT (
    R_ID INTEGER PRIMARY KEY, 
    R_AMOUNT NUMBER,
    R_STATUS INTEGER, --0 will be pending. 1 means approved and 2 means declined.
    EMPLOYEE_ID INTEGER
);
/

--Foreign Key Constraint

ALTER TABLE EMPLOYEE_D
ADD CONSTRAINT FK_MANAGER_EMPLOYEE
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE_D(E_ID);
/

ALTER TABLE REIMBURSEMENT
ADD CONSTRAINT FK_REIMBUREMENT_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE_D(E_ID);
/

--CREATE THE SEQUENCES FOR PRIMARY KEYS.
CREATE SEQUENCE SQ_EMPLOY_PK
START WITH 1
INCREMENT BY 1;
/
CREATE SEQUENCE SQ_REIMBURSEMENT_PK
START WITH 1
INCREMENT BY 1;
/

--Now create trigger to make use of these sequences. 

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOY
BEFORE INSERT ON EMPLOYEE_D 
FOR EACH ROW
BEGIN
    SELECT SQ_EMPLOY_PK.NEXTVAL INTO :NEW.E_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TR_INSERT_REIMBURSEMENT
BEFORE INSERT ON REIMBURSEMENT  
FOR EACH ROW
BEGIN
    SELECT SQ_REIMBURSEMENT_PK.NEXTVAL INTO :NEW.R_ID FROM DUAL;
END;
/

--Populate the databasew with a few Employees and Reimbursements

INSERT ALL
INTO EMPLOYEE_D (E_USERNAME, E_PASSWORD, E_EMAIL, MANAGER_ID)
VALUES ('DWallace', 'mypass123', 'DavidWallace@gmail.com', 1)
INTO EMPLOYEE_D (E_USERNAME, E_PASSWORD, E_EMAIL, MANAGER_ID)
VALUES ('MScott', 'mypass123', 'MichaelScott@gmail.com', 1)
INTO EMPLOYEE_D (E_USERNAME, E_PASSWORD, E_EMAIL, MANAGER_ID)
VALUES ('JHalpert', 'mypass123', 'JimHalpert@gmail.com', 2)
INTO EMPLOYEE_D (E_USERNAME, E_PASSWORD, E_EMAIL, MANAGER_ID)
VALUES ('DSchrute', 'mypass123', 'DwightSchrute@gmail.com', 2)
INTO EMPLOYEE_D (E_USERNAME, E_PASSWORD, E_EMAIL, MANAGER_ID)
VALUES ('PBeesly', 'mypass123', 'PamBeesly@gmail.com', 2)
SELECT * FROM DUAL;

--Add column in reimbursement for reason why reimbursement is being made. 

ALTER TABLE REIMBURSEMENT 
ADD DETAILS VARCHAR2(50) NOT NULL;

INSERT ALL
INTO REIMBURSEMENT (R_AMOUNT, R_STATUS, EMPLOYEE_ID, DETAILS)
VALUES (200, 2, 1, 'Parkore Lessons')
INTO REIMBURSEMENT (R_AMOUNT, R_STATUS, EMPLOYEE_ID, DETAILS)
VALUES (120, 0, 3, 'Dinner with Pam')
INTO REIMBURSEMENT (R_AMOUNT, R_STATUS, EMPLOYEE_ID, DETAILS)
VALUES (300, 2, 4, 'CPR Training')
INTO REIMBURSEMENT (R_AMOUNT, R_STATUS, EMPLOYEE_ID, DETAILS)
VALUES (100, 1, 5, 'Buisness Dinner')
SELECT * FROM DUAL;
